name: Actualizar ExoClock JSON

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *" # cada 6 horas (UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Descargar JSON de ExoClock actualizado
        run: |
          curl -s https://www.exoclock.space/database/planets_json \
            -o exoclockData.json

      - name: Commit y push si hay cambios
        run: |
          if git diff --quiet -- exoclockData.json; then
            echo "Sin cambios en exoclockData.json"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add exoclockData.json
          git commit -m "Actualización automática ExoClock"
          git push
